-- Stage 4 full scale-up: services 45 -> 722, countries 31 -> 80.
-- Verified against 5sim's real, live catalog (AGENT.md rule 5), not
-- invented — same methodology as the Stage 3 trial and the country-scaling
-- trial, extended to the full target scale. See this migration's
-- accompanying report for the full methodology and findings; summary:
--
-- Countries: surveyed all 153 countries 5sim lists (GET /guest/countries),
-- excluded 8 that 400 on GET /guest/products/<country>/any despite being
-- listed, ranked the remaining 145 by live product count, and took the
-- next 49 highest-inventory countries not already active
-- (weakest new addition: Congo at 192 live products — still well ahead of
-- the long tail of genuinely weak countries surveyed, e.g. Denmark at 24,
-- Belgium at 21, Djibouti at 1).
--
-- Services: built the union of every product code offered across the
-- final 80-country set (1,307 distinct codes), ranked by how many of
-- those 80 countries actually offer it (then by total live stock as a
-- tiebreaker), and included everything offered in 3 or more of them —
-- 722 total (677 new + the 45 already active, all of which still qualify
-- at this breadth). This intentionally lands under the original ~800
-- target: the next tier down is a large, roughly-tied cluster of
-- 2-country-only products with no principled way to pick 78 of them over
-- the other 73 without arbitrarily padding toward a round number, which
-- the instructions for this stage explicitly said not to do.
--
-- Display names for this bulk batch are algorithmically capitalized from
-- 5sim's product code (first letter uppercased, rest untouched) rather
-- than hand-verified against each brand's real styling — not practical to
-- individually verify 677 names by hand. The original 45 services keep
-- their precise, hand-verified names from Stage 3 and earlier. Category
-- is a flat 'Other' for all of them: 5sim's own product metadata has no
-- consumer-facing genre (its "Category" field is always literally
-- "activation", a 5sim-internal distinction, not ours), so inventing a
-- Messaging/Social/Shopping/etc. split for 677 largely-unfamiliar codes
-- by hand would mean guessing, not verifying.
--
-- icon_key defaults to the product code itself (lib/icons/lookup.ts
-- returns null — the existing, designed-for neutral-tile fallback — for
-- anything that isn't a real Simple Icons slug) rather than hand-checking
-- 677 slugs; the resulting match rate is reported alongside this
-- migration rather than chased up front, per this stage's explicit
-- acceptance of Simple Icons' ~75% coverage.
insert into public.countries (name, fivesim_country_code, flag_emoji) values
  ('Mexico', 'mexico', '🇲🇽'),
  ('Thailand', 'thailand', '🇹🇭'),
  ('Greece', 'greece', '🇬🇷'),
  ('Honduras', 'honduras', '🇭🇳'),
  ('Georgia', 'georgia', '🇬🇪'),
  ('Pakistan', 'pakistan', '🇵🇰'),
  ('Colombia', 'colombia', '🇨🇴'),
  ('Bangladesh', 'bangladesh', '🇧🇩'),
  ('Malawi', 'malawi', '🇲🇼'),
  ('Cameroon', 'cameroon', '🇨🇲'),
  ('Guatemala', 'guatemala', '🇬🇹'),
  ('Sri Lanka', 'srilanka', '🇱🇰'),
  ('Algeria', 'algeria', '🇩🇿'),
  ('Afghanistan', 'afghanistan', '🇦🇫'),
  ('Bolivia', 'bolivia', '🇧🇴'),
  ('Nepal', 'nepal', '🇳🇵'),
  ('Nicaragua', 'nicaragua', '🇳🇮'),
  ('Moldova', 'moldova', '🇲🇩'),
  ('Serbia', 'serbia', '🇷🇸'),
  ('Togo', 'togo', '🇹🇬'),
  ('Ecuador', 'ecuador', '🇪🇨'),
  ('Ethiopia', 'ethiopia', '🇪🇹'),
  ('Guinea', 'guinea', '🇬🇳'),
  ('Mozambique', 'mozambique', '🇲🇿'),
  ('Gambia', 'gambia', '🇬🇲'),
  ('Jordan', 'jordan', '🇯🇴'),
  ('Liberia', 'liberia', '🇱🇷'),
  ('Jamaica', 'jamaica', '🇯🇲'),
  ('Tunisia', 'tunisia', '🇹🇳'),
  ('Kuwait', 'kuwait', '🇰🇼'),
  ('Mauritania', 'mauritania', '🇲🇷'),
  ('Venezuela', 'venezuela', '🇻🇪'),
  ('Maldives', 'maldives', '🇲🇻'),
  ('Panama', 'panama', '🇵🇦'),
  ('Senegal', 'senegal', '🇸🇳'),
  ('Barbados', 'barbados', '🇧🇧'),
  ('Costa Rica', 'costarica', '🇨🇷'),
  ('Mongolia', 'mongolia', '🇲🇳'),
  ('Guyana', 'guyana', '🇬🇾'),
  ('Mauritius', 'mauritius', '🇲🇺'),
  ('Botswana', 'botswana', '🇧🇼'),
  ('Burkina Faso', 'burkinafaso', '🇧🇫'),
  ('Cape Verde', 'capeverde', '🇨🇻'),
  ('Suriname', 'suriname', '🇸🇷'),
  ('Armenia', 'armenia', '🇦🇲'),
  ('Swaziland', 'swaziland', '🇸🇿'),
  ('Equatorial Guinea', 'equatorialguinea', '🇬🇶'),
  ('Namibia', 'namibia', '🇳🇦'),
  ('Congo', 'congo', '🇨🇬')
on conflict (fivesim_country_code) do nothing;

insert into public.services (name, fivesim_product_code, category, icon_key) values
  ('Aol', 'aol', 'Other', 'aol'),
  ('Naver', 'naver', 'Other', 'naver'),
  ('Zoho', 'zoho', 'Other', 'zoho'),
  ('Craigslist', 'craigslist', 'Other', 'craigslist'),
  ('Tencentqq', 'tencentqq', 'Other', 'tencentqq'),
  ('Papara', 'papara', 'Other', 'papara'),
  ('Blizzard', 'blizzard', 'Other', 'blizzard'),
  ('Weibo', 'weibo', 'Other', 'weibo'),
  ('Bigolive', 'bigolive', 'Other', 'bigolive'),
  ('Skout', 'skout', 'Other', 'skout'),
  ('Vinted', 'vinted', 'Other', 'vinted'),
  ('Pof', 'pof', 'Other', 'pof'),
  ('Clubhouse', 'clubhouse', 'Other', 'clubhouse'),
  ('Getir', 'getir', 'Other', 'getir'),
  ('Olx', 'olx', 'Other', 'olx'),
  ('Lazada', 'lazada', 'Other', 'lazada'),
  ('Zalo', 'zalo', 'Other', 'zalo'),
  ('Ticketmaster', 'ticketmaster', 'Other', 'ticketmaster'),
  ('Kwai', 'kwai', 'Other', 'kwai'),
  ('Yemeksepeti', 'yemeksepeti', 'Other', 'yemeksepeti'),
  ('Didi', 'didi', 'Other', 'didi'),
  ('Michat', 'michat', 'Other', 'michat'),
  ('Hepsiburadacom', 'hepsiburadacom', 'Other', 'hepsiburadacom'),
  ('Carousell', 'carousell', 'Other', 'carousell'),
  ('Tantan', 'tantan', 'Other', 'tantan'),
  ('Trendyol', 'trendyol', 'Other', 'trendyol'),
  ('Truecaller', 'truecaller', 'Other', 'truecaller'),
  ('Keybase', 'keybase', 'Other', 'keybase'),
  ('Olacabs', 'olacabs', 'Other', 'olacabs'),
  ('Gett', 'gett', 'Other', 'gett'),
  ('Taobao', 'taobao', 'Other', 'taobao'),
  ('Sikayetvar', 'sikayetvar', 'Other', 'sikayetvar'),
  ('Bitclout', 'bitclout', 'Other', 'bitclout'),
  ('Gofundme', 'gofundme', 'Other', 'gofundme'),
  ('Groupme', 'groupme', 'Other', 'groupme'),
  ('Dream11', 'dream11', 'Other', 'dream11'),
  ('Dominospizza', 'dominospizza', 'Other', 'dominospizza'),
  ('Blued', 'blued', 'Other', 'blued'),
  ('Humblebundle', 'humblebundle', 'Other', 'humblebundle'),
  ('Baidu', 'baidu', 'Other', 'baidu'),
  ('Imo', 'imo', 'Other', 'imo'),
  ('Wolt', 'wolt', 'Other', 'wolt'),
  ('Mcdonalds', 'mcdonalds', 'Other', 'mcdonalds'),
  ('Nttgame', 'nttgame', 'Other', 'nttgame'),
  ('Blablacar', 'blablacar', 'Other', 'blablacar'),
  ('Tango', 'tango', 'Other', 'tango'),
  ('Noon', 'noon', 'Other', 'noon'),
  ('99App', '99app', 'Other', '99app'),
  ('Ifood', 'ifood', 'Other', 'ifood'),
  ('Indriver', 'indriver', 'Other', 'indriver'),
  ('Justdating', 'justdating', 'Other', 'justdating'),
  ('Burgerking', 'burgerking', 'Other', 'burgerking'),
  ('Hopi', 'hopi', 'Other', 'hopi'),
  ('Dundle', 'dundle', 'Other', 'dundle'),
  ('Douyu', 'douyu', 'Other', 'douyu'),
  ('Cupid', 'cupid', 'Other', 'cupid'),
  ('Faceit', 'faceit', 'Other', 'faceit'),
  ('Quipp', 'quipp', 'Other', 'quipp'),
  ('Paxful', 'paxful', 'Other', 'paxful'),
  ('Amasia', 'amasia', 'Other', 'amasia'),
  ('Huya', 'huya', 'Other', 'huya'),
  ('1688', '1688', 'Other', '1688'),
  ('Mega', 'mega', 'Other', 'mega'),
  ('Algida', 'algida', 'Other', 'algida'),
  ('Yalla', 'yalla', 'Other', 'yalla'),
  ('Iqos', 'iqos', 'Other', 'iqos'),
  ('Hily', 'hily', 'Other', 'hily'),
  ('Offgamers', 'offgamers', 'Other', 'offgamers'),
  ('Eneba', 'eneba', 'Other', 'eneba'),
  ('Xiaomi', 'xiaomi', 'Other', 'xiaomi'),
  ('Weststein', 'weststein', 'Other', 'weststein'),
  ('Offerup', 'offerup', 'Other', 'offerup'),
  ('32Red', '32red', 'Other', '32red'),
  ('Likee', 'likee', 'Other', 'likee'),
  ('Dhani', 'dhani', 'Other', 'dhani'),
  ('Tosla', 'tosla', 'Other', 'tosla'),
  ('Aitu', 'aitu', 'Other', 'aitu'),
  ('Clickentregas', 'clickentregas', 'Other', 'clickentregas'),
  ('Premiumone', 'premiumone', 'Other', 'premiumone'),
  ('Gamekit', 'gamekit', 'Other', 'gamekit'),
  ('Globus', 'globus', 'Other', 'globus'),
  ('Googlevoice', 'googlevoice', 'Other', 'googlevoice'),
  ('Betfair', 'betfair', 'Other', 'betfair'),
  ('Gg', 'gg', 'Other', 'gg'),
  ('Myglo', 'myglo', 'Other', 'myglo'),
  ('Poshmark', 'poshmark', 'Other', 'poshmark'),
  ('Hermes', 'hermes', 'Other', 'hermes'),
  ('Lightchat', 'lightchat', 'Other', 'lightchat'),
  ('Maplesea', 'maplesea', 'Other', 'maplesea'),
  ('Mpl', 'mpl', 'Other', 'mpl'),
  ('Iqiyi', 'iqiyi', 'Other', 'iqiyi'),
  ('Cliqq', 'cliqq', 'Other', 'cliqq'),
  ('Kucoinplay', 'kucoinplay', 'Other', 'kucoinplay'),
  ('Sneakerboy', 'sneakerboy', 'Other', 'sneakerboy'),
  ('Bisu', 'bisu', 'Other', 'bisu'),
  ('Gamearena', 'gamearena', 'Other', 'gamearena'),
  ('Pokec', 'pokec', 'Other', 'pokec'),
  ('Picpay', 'picpay', 'Other', 'picpay'),
  ('Redbook', 'redbook', 'Other', 'redbook'),
  ('Bet365', 'bet365', 'Other', 'bet365'),
  ('Kaggle', 'kaggle', 'Other', 'kaggle'),
  ('Jd', 'jd', 'Other', 'jd'),
  ('Hezzl', 'hezzl', 'Other', 'hezzl'),
  ('Zcity', 'zcity', 'Other', 'zcity'),
  ('Zupee', 'zupee', 'Other', 'zupee'),
  ('Metro', 'metro', 'Other', 'metro'),
  ('Yubo', 'yubo', 'Other', 'yubo'),
  ('Potato', 'potato', 'Other', 'potato'),
  ('Swagbucks', 'swagbucks', 'Other', 'swagbucks'),
  ('Surveytime', 'surveytime', 'Other', 'surveytime'),
  ('Kolesakz', 'kolesakz', 'Other', 'kolesakz'),
  ('Cafebazaar', 'cafebazaar', 'Other', 'cafebazaar'),
  ('Digikala', 'digikala', 'Other', 'digikala'),
  ('Wmaraci', 'wmaraci', 'Other', 'wmaraci'),
  ('Mzadqatar', 'mzadqatar', 'Other', 'mzadqatar'),
  ('Gittigidiyor', 'gittigidiyor', 'Other', 'gittigidiyor'),
  ('Yaay', 'yaay', 'Other', 'yaay'),
  ('Bitaqaty', 'bitaqaty', 'Other', 'bitaqaty'),
  ('Allegro', 'allegro', 'Other', 'allegro'),
  ('Tradingview', 'tradingview', 'Other', 'tradingview'),
  ('Unacademy', 'unacademy', 'Other', 'unacademy'),
  ('Kaidee', 'kaidee', 'Other', 'kaidee'),
  ('Disneyhotstar', 'disneyhotstar', 'Other', 'disneyhotstar'),
  ('Foodora', 'foodora', 'Other', 'foodora'),
  ('Gojek', 'gojek', 'Other', 'gojek'),
  ('Quikr', 'quikr', 'Other', 'quikr'),
  ('Mocospace', 'mocospace', 'Other', 'mocospace'),
  ('Trip', 'trip', 'Other', 'trip'),
  ('Pgbonus', 'pgbonus', 'Other', 'pgbonus'),
  ('Joyride', 'joyride', 'Other', 'joyride'),
  ('Tataneu', 'tataneu', 'Other', 'tataneu'),
  ('Payzapp', 'payzapp', 'Other', 'payzapp'),
  ('Irctc', 'irctc', 'Other', 'irctc'),
  ('Communitygaming', 'communitygaming', 'Other', 'communitygaming'),
  ('Meesho', 'meesho', 'Other', 'meesho'),
  ('Talabat', 'talabat', 'Other', 'talabat'),
  ('Youstar', 'youstar', 'Other', 'youstar'),
  ('Q12trivia', 'q12trivia', 'Other', 'q12trivia'),
  ('Zepto', 'zepto', 'Other', 'zepto'),
  ('Swiggy', 'swiggy', 'Other', 'swiggy'),
  ('My11circle', 'my11circle', 'Other', 'my11circle'),
  ('Rummycircle', 'rummycircle', 'Other', 'rummycircle'),
  ('Magicpin', 'magicpin', 'Other', 'magicpin'),
  ('Lovelocal', 'lovelocal', 'Other', 'lovelocal'),
  ('99Acres', '99acres', 'Other', '99acres'),
  ('Glowroad', 'glowroad', 'Other', 'glowroad'),
  ('Jiomart', 'jiomart', 'Other', 'jiomart'),
  ('Earneasy', 'earneasy', 'Other', 'earneasy'),
  ('Bajajfinserv', 'bajajfinserv', 'Other', 'bajajfinserv'),
  ('Rediffmail', 'rediffmail', 'Other', 'rediffmail'),
  ('Sneakersnstuff', 'sneakersnstuff', 'Other', 'sneakersnstuff'),
  ('Alfa', 'alfa', 'Other', 'alfa'),
  ('Spartanpoker', 'spartanpoker', 'Other', 'spartanpoker'),
  ('Medibuddy', 'medibuddy', 'Other', 'medibuddy'),
  ('Myjar', 'myjar', 'Other', 'myjar'),
  ('Gamezy', 'gamezy', 'Other', 'gamezy'),
  ('Coindcx', 'coindcx', 'Other', 'coindcx'),
  ('Inboxlv', 'inboxlv', 'Other', 'inboxlv'),
  ('Ncsoft', 'ncsoft', 'Other', 'ncsoft'),
  ('Socios', 'socios', 'Other', 'socios'),
  ('Mobikwik', 'mobikwik', 'Other', 'mobikwik'),
  ('Switips', 'switips', 'Other', 'switips'),
  ('888Casino', '888casino', 'Other', '888casino'),
  ('Hinge', 'hinge', 'Other', 'hinge'),
  ('Other', 'other', 'Other', 'other'),
  ('Foody', 'foody', 'Other', 'foody'),
  ('Alipay', 'alipay', 'Other', 'alipay'),
  ('Paddypower', 'paddypower', 'Other', 'paddypower'),
  ('Uklon', 'uklon', 'Other', 'uklon'),
  ('Botim', 'botim', 'Other', 'botim'),
  ('Ace2three', 'ace2three', 'Other', 'ace2three'),
  ('Agroinform', 'agroinform', 'Other', 'agroinform'),
  ('Lyka', 'lyka', 'Other', 'lyka'),
  ('Banqi', 'banqi', 'Other', 'banqi'),
  ('Mercado', 'mercado', 'Other', 'mercado'),
  ('Mrgreen', 'mrgreen', 'Other', 'mrgreen'),
  ('Claudeai', 'claudeai', 'Other', 'claudeai'),
  ('Pureplatfrom', 'pureplatfrom', 'Other', 'pureplatfrom'),
  ('Proton', 'proton', 'Other', 'proton'),
  ('Radquest', 'radquest', 'Other', 'radquest'),
  ('Bereal', 'bereal', 'Other', 'bereal'),
  ('Royalwin', 'royalwin', 'Other', 'royalwin'),
  ('Wise', 'wise', 'Other', 'wise'),
  ('Prom', 'prom', 'Other', 'prom'),
  ('Efsanetr', 'efsanetr', 'Other', 'efsanetr'),
  ('Sheerid', 'sheerid', 'Other', 'sheerid'),
  ('Seosprint', 'seosprint', 'Other', 'seosprint'),
  ('Paysend', 'paysend', 'Other', 'paysend'),
  ('163Som', '163som', 'Other', '163som'),
  ('Classpass', 'classpass', 'Other', 'classpass'),
  ('Grailed', 'grailed', 'Other', 'grailed'),
  ('Immowelt', 'immowelt', 'Other', 'immowelt'),
  ('Oriflame', 'oriflame', 'Other', 'oriflame'),
  ('Twilio', 'twilio', 'Other', 'twilio'),
  ('Ukrnet', 'ukrnet', 'Other', 'ukrnet'),
  ('Genspark', 'genspark', 'Other', 'genspark'),
  ('Myntra', 'myntra', 'Other', 'myntra'),
  ('Swvl', 'swvl', 'Other', 'swvl'),
  ('Global24', 'global24', 'Other', 'global24'),
  ('Nrjmusicawards', 'nrjmusicawards', 'Other', 'nrjmusicawards'),
  ('Razer', 'razer', 'Other', 'razer'),
  ('Pubg', 'pubg', 'Other', 'pubg'),
  ('Ezbuy', 'ezbuy', 'Other', 'ezbuy'),
  ('Snappfood', 'snappfood', 'Other', 'snappfood'),
  ('Touchance', 'touchance', 'Other', 'touchance'),
  ('Onlinerby', 'onlinerby', 'Other', 'onlinerby'),
  ('Howzat', 'howzat', 'Other', 'howzat'),
  ('Cdkeys', 'cdkeys', 'Other', 'cdkeys'),
  ('Gameflip', 'gameflip', 'Other', 'gameflip'),
  ('Jkf', 'jkf', 'Other', 'jkf'),
  ('Feetfinder', 'feetfinder', 'Other', 'feetfinder'),
  ('Etsy', 'etsy', 'Other', 'etsy'),
  ('Poikey', 'poikey', 'Other', 'poikey'),
  ('Mewt', 'mewt', 'Other', 'mewt'),
  ('Pairs', 'pairs', 'Other', 'pairs'),
  ('Lybrate', 'lybrate', 'Other', 'lybrate'),
  ('Nobroker', 'nobroker', 'Other', 'nobroker'),
  ('Gabi', 'gabi', 'Other', 'gabi'),
  ('Kufarby', 'kufarby', 'Other', 'kufarby'),
  ('Brand20ua', 'brand20ua', 'Other', 'brand20ua'),
  ('Spothit', 'spothit', 'Other', 'spothit'),
  ('Siply', 'siply', 'Other', 'siply'),
  ('Frizza', 'frizza', 'Other', 'frizza'),
  ('Rummywealth', 'rummywealth', 'Other', 'rummywealth'),
  ('Shellbox', 'shellbox', 'Other', 'shellbox'),
  ('Flink', 'flink', 'Other', 'flink'),
  ('Samsungshop', 'samsungshop', 'Other', 'samsungshop'),
  ('Dosi', 'dosi', 'Other', 'dosi'),
  ('Sorare', 'sorare', 'Other', 'sorare'),
  ('Verse', 'verse', 'Other', 'verse'),
  ('Upland', 'upland', 'Other', 'upland'),
  ('Cloudbet', 'cloudbet', 'Other', 'cloudbet'),
  ('Taksheel', 'taksheel', 'Other', 'taksheel'),
  ('Galaxywin', 'galaxywin', 'Other', 'galaxywin'),
  ('Quack', 'quack', 'Other', 'quack'),
  ('B4ucabs', 'b4ucabs', 'Other', 'b4ucabs'),
  ('Hamrahaval', 'hamrahaval', 'Other', 'hamrahaval'),
  ('Humta', 'humta', 'Other', 'humta'),
  ('Divar', 'divar', 'Other', 'divar'),
  ('Meetme', 'meetme', 'Other', 'meetme'),
  ('Flip', 'flip', 'Other', 'flip'),
  ('Joymall', 'joymall', 'Other', 'joymall'),
  ('Leboncoin', 'leboncoin', 'Other', 'leboncoin'),
  ('Voi', 'voi', 'Other', 'voi'),
  ('Geekay', 'geekay', 'Other', 'geekay'),
  ('Fortunask', 'fortunask', 'Other', 'fortunask'),
  ('Taskdealsin', 'taskdealsin', 'Other', 'taskdealsin'),
  ('Otovinn', 'otovinn', 'Other', 'otovinn'),
  ('Starchatsite', 'starchatsite', 'Other', 'starchatsite'),
  ('Chaingefinance', 'chaingefinance', 'Other', 'chaingefinance'),
  ('1Kkirana', '1kkirana', 'Other', '1kkirana'),
  ('Ontaxi', 'ontaxi', 'Other', 'ontaxi'),
  ('Nana', 'nana', 'Other', 'nana'),
  ('Peoplecom', 'peoplecom', 'Other', 'peoplecom'),
  ('Realresearcher', 'realresearcher', 'Other', 'realresearcher'),
  ('Electroneum', 'electroneum', 'Other', 'electroneum'),
  ('Zhipuai', 'zhipuai', 'Other', 'zhipuai'),
  ('Rummyculture', 'rummyculture', 'Other', 'rummyculture'),
  ('Iost', 'iost', 'Other', 'iost'),
  ('Edgeless', 'edgeless', 'Other', 'edgeless'),
  ('Bazos', 'bazos', 'Other', 'bazos'),
  ('Thefork', 'thefork', 'Other', 'thefork'),
  ('Meta', 'meta', 'Other', 'meta'),
  ('Playerauctions', 'playerauctions', 'Other', 'playerauctions'),
  ('Yougotagift', 'yougotagift', 'Other', 'yougotagift'),
  ('Warpcast', 'warpcast', 'Other', 'warpcast'),
  ('Hopper', 'hopper', 'Other', 'hopper'),
  ('Hkticketing', 'hkticketing', 'Other', 'hkticketing'),
  ('Icecasino', 'icecasino', 'Other', 'icecasino'),
  ('Fambase', 'fambase', 'Other', 'fambase'),
  ('Pyromusic', 'pyromusic', 'Other', 'pyromusic'),
  ('Fiqsy', 'fiqsy', 'Other', 'fiqsy'),
  ('Mylove', 'mylove', 'Other', 'mylove'),
  ('Prajmeriz2020', 'prajmeriz2020', 'Other', 'prajmeriz2020'),
  ('Weku', 'weku', 'Other', 'weku'),
  ('Pokermaster', 'pokermaster', 'Other', 'pokermaster'),
  ('Voopee', 'voopee', 'Other', 'voopee'),
  ('Gemini', 'gemini', 'Other', 'gemini'),
  ('23Red', '23red', 'Other', '23red'),
  ('Ripkord', 'ripkord', 'Other', 'ripkord'),
  ('Nimses', 'nimses', 'Other', 'nimses'),
  ('Temu', 'temu', 'Other', 'temu'),
  ('Probo', 'probo', 'Other', 'probo'),
  ('Lyft', 'lyft', 'Other', 'lyft'),
  ('Onet', 'onet', 'Other', 'onet'),
  ('Rozetka', 'rozetka', 'Other', 'rozetka'),
  ('Avon', 'avon', 'Other', 'avon'),
  ('Bip', 'bip', 'Other', 'bip'),
  ('Okta', 'okta', 'Other', 'okta'),
  ('Byteplus', 'byteplus', 'Other', 'byteplus'),
  ('Biketown', 'biketown', 'Other', 'biketown'),
  ('Pelago', 'pelago', 'Other', 'pelago'),
  ('Mobile01', 'mobile01', 'Other', 'mobile01'),
  ('Mrsool', 'mrsool', 'Other', 'mrsool'),
  ('Jamesdelivery', 'jamesdelivery', 'Other', 'jamesdelivery'),
  ('Ebikegewinnspiel', 'ebikegewinnspiel', 'Other', 'ebikegewinnspiel'),
  ('Billmill', 'billmill', 'Other', 'billmill'),
  ('Nhseven', 'nhseven', 'Other', 'nhseven'),
  ('Uploaded', 'uploaded', 'Other', 'uploaded'),
  ('Oyo', 'oyo', 'Other', 'oyo'),
  ('Openpoint', 'openpoint', 'Other', 'openpoint'),
  ('Wondermart', 'wondermart', 'Other', 'wondermart'),
  ('Adani', 'adani', 'Other', 'adani'),
  ('Flipkart', 'flipkart', 'Other', 'flipkart'),
  ('Hirect', 'hirect', 'Other', 'hirect'),
  ('Steemit', 'steemit', 'Other', 'steemit'),
  ('Classicrummy', 'classicrummy', 'Other', 'classicrummy'),
  ('Cadburyperk', 'cadburyperk', 'Other', 'cadburyperk'),
  ('Khelraja', 'khelraja', 'Other', 'khelraja'),
  ('Lianxin', 'lianxin', 'Other', 'lianxin'),
  ('Galaxy', 'galaxy', 'Other', 'galaxy'),
  ('Sportgully', 'sportgully', 'Other', 'sportgully'),
  ('Shein', 'shein', 'Other', 'shein'),
  ('Winzo', 'winzo', 'Other', 'winzo'),
  ('Mymusictaste', 'mymusictaste', 'Other', 'mymusictaste'),
  ('Auchan', 'auchan', 'Other', 'auchan'),
  ('Gamer', 'gamer', 'Other', 'gamer'),
  ('Ssoidnet', 'ssoidnet', 'Other', 'ssoidnet'),
  ('Citybase', 'citybase', 'Other', 'citybase'),
  ('Ziglu', 'ziglu', 'Other', 'ziglu'),
  ('Justdial', 'justdial', 'Other', 'justdial'),
  ('Lbry', 'lbry', 'Other', 'lbry'),
  ('Bittube', 'bittube', 'Other', 'bittube'),
  ('Feeld', 'feeld', 'Other', 'feeld'),
  ('Gyftr', 'gyftr', 'Other', 'gyftr'),
  ('Yango', 'yango', 'Other', 'yango'),
  ('Indiaplays', 'indiaplays', 'Other', 'indiaplays'),
  ('Lightningai', 'lightningai', 'Other', 'lightningai'),
  ('Cashmine', 'cashmine', 'Other', 'cashmine'),
  ('Adda52', 'adda52', 'Other', 'adda52'),
  ('Gmngjourney', 'gmngjourney', 'Other', 'gmngjourney'),
  ('Cashkaro', 'cashkaro', 'Other', 'cashkaro'),
  ('Akelni', 'akelni', 'Other', 'akelni'),
  ('Winston', 'winston', 'Other', 'winston'),
  ('Oraclecloud', 'oraclecloud', 'Other', 'oraclecloud'),
  ('Azino', 'azino', 'Other', 'azino'),
  ('Totalcoin', 'totalcoin', 'Other', 'totalcoin'),
  ('Rummy', 'rummy', 'Other', 'rummy'),
  ('Akudo', 'akudo', 'Other', 'akudo'),
  ('Ubisoft', 'ubisoft', 'Other', 'ubisoft'),
  ('Dealshare', 'dealshare', 'Other', 'dealshare'),
  ('Bigbasket', 'bigbasket', 'Other', 'bigbasket'),
  ('Sendinblue', 'sendinblue', 'Other', 'sendinblue'),
  ('Bitexen', 'bitexen', 'Other', 'bitexen'),
  ('Magicbricks', 'magicbricks', 'Other', 'magicbricks'),
  ('Grofers', 'grofers', 'Other', 'grofers'),
  ('Pharmeasy', 'pharmeasy', 'Other', 'pharmeasy'),
  ('Roposo', 'roposo', 'Other', 'roposo'),
  ('Jungleerummy', 'jungleerummy', 'Other', 'jungleerummy'),
  ('Crickpe', 'crickpe', 'Other', 'crickpe'),
  ('Rainmaker', 'rainmaker', 'Other', 'rainmaker'),
  ('Suprdaily', 'suprdaily', 'Other', 'suprdaily'),
  ('Toprun', 'toprun', 'Other', 'toprun'),
  ('Fan2play', 'fan2play', 'Other', 'fan2play'),
  ('Twelfthman', 'twelfthman', 'Other', 'twelfthman'),
  ('Beccric', 'beccric', 'Other', 'beccric'),
  ('Cekkazan', 'cekkazan', 'Other', 'cekkazan'),
  ('Dunzo', 'dunzo', 'Other', 'dunzo'),
  ('Otipy', 'otipy', 'Other', 'otipy'),
  ('Reuse', 'reuse', 'Other', 'reuse'),
  ('Sahicoin', 'sahicoin', 'Other', 'sahicoin'),
  ('Cokfiight', 'cokfiight', 'Other', 'cokfiight'),
  ('Green', 'green', 'Other', 'green'),
  ('Ridery', 'ridery', 'Other', 'ridery'),
  ('Bilibili', 'bilibili', 'Other', 'bilibili'),
  ('Venmo', 'venmo', 'Other', 'venmo'),
  ('Airtel', 'airtel', 'Other', 'airtel'),
  ('Parimatch', 'parimatch', 'Other', 'parimatch'),
  ('Playerzpot', 'playerzpot', 'Other', 'playerzpot'),
  ('Truefan', 'truefan', 'Other', 'truefan'),
  ('Ezmall', 'ezmall', 'Other', 'ezmall'),
  ('Panelstation', 'panelstation', 'Other', 'panelstation'),
  ('Tongchengtravel', 'tongchengtravel', 'Other', 'tongchengtravel'),
  ('Timesprime', 'timesprime', 'Other', 'timesprime'),
  ('1Mg', '1mg', 'Other', '1mg'),
  ('Indianoil', 'indianoil', 'Other', 'indianoil'),
  ('Vinota', 'vinota', 'Other', 'vinota'),
  ('More', 'more', 'Other', 'more'),
  ('Apollo', 'apollo', 'Other', 'apollo'),
  ('Ewargames', 'ewargames', 'Other', 'ewargames'),
  ('Healthandglow', 'healthandglow', 'Other', 'healthandglow'),
  ('Myfab11', 'myfab11', 'Other', 'myfab11'),
  ('Bigbazaar', 'bigbazaar', 'Other', 'bigbazaar'),
  ('Nykaa', 'nykaa', 'Other', 'nykaa'),
  ('Boddess', 'boddess', 'Other', 'boddess'),
  ('Cardekho', 'cardekho', 'Other', 'cardekho'),
  ('Edufund', 'edufund', 'Other', 'edufund'),
  ('Elante', 'elante', 'Other', 'elante'),
  ('Flam', 'flam', 'Other', 'flam'),
  ('Jeet11', 'jeet11', 'Other', 'jeet11'),
  ('Kisma', 'kisma', 'Other', 'kisma'),
  ('Lakme', 'lakme', 'Other', 'lakme'),
  ('Tatacliq', 'tatacliq', 'Other', 'tatacliq'),
  ('Vscric', 'vscric', 'Other', 'vscric'),
  ('Domdara', 'domdara', 'Other', 'domdara'),
  ('Forwarding', 'forwarding', 'Other', 'forwarding'),
  ('Hqtrivia', 'hqtrivia', 'Other', 'hqtrivia'),
  ('Cathay', 'cathay', 'Other', 'cathay'),
  ('Zhihu', 'zhihu', 'Other', 'zhihu'),
  ('Ryde', 'ryde', 'Other', 'ryde'),
  ('Redbubble', 'redbubble', 'Other', 'redbubble'),
  ('2Dehands', '2dehands', 'Other', '2dehands'),
  ('Authy', 'authy', 'Other', 'authy'),
  ('Rapido', 'rapido', 'Other', 'rapido'),
  ('Vernyj', 'vernyj', 'Other', 'vernyj'),
  ('Qoo10', 'qoo10', 'Other', 'qoo10'),
  ('Playship', 'playship', 'Other', 'playship'),
  ('Farmcare', 'farmcare', 'Other', 'farmcare'),
  ('Gghasia', 'gghasia', 'Other', 'gghasia'),
  ('Wizely', 'wizely', 'Other', 'wizely'),
  ('Gamerji', 'gamerji', 'Other', 'gamerji'),
  ('Locoff', 'locoff', 'Other', 'locoff'),
  ('Sikka', 'sikka', 'Other', 'sikka'),
  ('Continente', 'continente', 'Other', 'continente'),
  ('Gailsbakery', 'gailsbakery', 'Other', 'gailsbakery'),
  ('Dominate11', 'dominate11', 'Other', 'dominate11'),
  ('Fiegame', 'fiegame', 'Other', 'fiegame'),
  ('Hotline', 'hotline', 'Other', 'hotline'),
  ('Kazandirio', 'kazandirio', 'Other', 'kazandirio'),
  ('Locogg', 'locogg', 'Other', 'locogg'),
  ('Phable', 'phable', 'Other', 'phable'),
  ('Betvet', 'betvet', 'Other', 'betvet'),
  ('Bitlo', 'bitlo', 'Other', 'bitlo'),
  ('Meitu', 'meitu', 'Other', 'meitu'),
  ('Dent', 'dent', 'Other', 'dent'),
  ('Monese', 'monese', 'Other', 'monese'),
  ('Oneforma', 'oneforma', 'Other', 'oneforma'),
  ('Bitso', 'bitso', 'Other', 'bitso'),
  ('Netease', 'netease', 'Other', 'netease'),
  ('Freenow', 'freenow', 'Other', 'freenow'),
  ('Efood', 'efood', 'Other', 'efood'),
  ('Skype', 'skype', 'Other', 'skype'),
  ('Zoominfo', 'zoominfo', 'Other', 'zoominfo'),
  ('Monoapp', 'monoapp', 'Other', 'monoapp'),
  ('Ipsosisay', 'ipsosisay', 'Other', 'ipsosisay'),
  ('Casinoandfriends', 'casinoandfriends', 'Other', 'casinoandfriends'),
  ('Caltexgo', 'caltexgo', 'Other', 'caltexgo'),
  ('Flypgs', 'flypgs', 'Other', 'flypgs'),
  ('Iwplay', 'iwplay', 'Other', 'iwplay'),
  ('Opera', 'opera', 'Other', 'opera'),
  ('Megapari', 'megapari', 'Other', 'megapari'),
  ('Paytm', 'paytm', 'Other', 'paytm'),
  ('Adobe', 'adobe', 'Other', 'adobe'),
  ('Doordash', 'doordash', 'Other', 'doordash'),
  ('G2g', 'g2g', 'Other', 'g2g'),
  ('Shopify', 'shopify', 'Other', 'shopify'),
  ('Momo', 'momo', 'Other', 'momo'),
  ('Pingpong', 'pingpong', 'Other', 'pingpong'),
  ('Zebpay', 'zebpay', 'Other', 'zebpay'),
  ('Zara', 'zara', 'Other', 'zara'),
  ('Huawei', 'huawei', 'Other', 'huawei'),
  ('Paysafecard', 'paysafecard', 'Other', 'paysafecard'),
  ('Handypick', 'handypick', 'Other', 'handypick'),
  ('Livescore', 'livescore', 'Other', 'livescore'),
  ('Easypay', 'easypay', 'Other', 'easypay'),
  ('Skrill', 'skrill', 'Other', 'skrill'),
  ('Roblox', 'roblox', 'Other', 'roblox'),
  ('Outlier', 'outlier', 'Other', 'outlier'),
  ('Wish', 'wish', 'Other', 'wish'),
  ('Manus', 'manus', 'Other', 'manus'),
  ('Brevo', 'brevo', 'Other', 'brevo'),
  ('Supercell', 'supercell', 'Other', 'supercell'),
  ('Linode', 'linode', 'Other', 'linode'),
  ('Keypay', 'keypay', 'Other', 'keypay'),
  ('Carrefour', 'carrefour', 'Other', 'carrefour'),
  ('Truthsocial', 'truthsocial', 'Other', 'truthsocial'),
  ('Kaito', 'kaito', 'Other', 'kaito'),
  ('Mantrimall', 'mantrimall', 'Other', 'mantrimall'),
  ('Factoryai', 'factoryai', 'Other', 'factoryai'),
  ('Nifty', 'nifty', 'Other', 'nifty'),
  ('Blockchain', 'blockchain', 'Other', 'blockchain'),
  ('Poeai', 'poeai', 'Other', 'poeai'),
  ('Idealista', 'idealista', 'Other', 'idealista'),
  ('Subito', 'subito', 'Other', 'subito'),
  ('Whatnot', 'whatnot', 'Other', 'whatnot'),
  ('Epicgames', 'epicgames', 'Other', 'epicgames'),
  ('Badoo', 'badoo', 'Other', 'badoo'),
  ('Indeed', 'indeed', 'Other', 'indeed'),
  ('Upwork', 'upwork', 'Other', 'upwork'),
  ('Kfc', 'kfc', 'Other', 'kfc'),
  ('Eyecon', 'eyecon', 'Other', 'eyecon'),
  ('Wert', 'wert', 'Other', 'wert'),
  ('Primeopinion', 'primeopinion', 'Other', 'primeopinion'),
  ('Meetic', 'meetic', 'Other', 'meetic'),
  ('Fineartamerica', 'fineartamerica', 'Other', 'fineartamerica'),
  ('Vfsglobal', 'vfsglobal', 'Other', 'vfsglobal'),
  ('Siliconflow', 'siliconflow', 'Other', 'siliconflow'),
  ('Dott', 'dott', 'Other', 'dott'),
  ('Freelancercom', 'freelancercom', 'Other', 'freelancercom'),
  ('Qqpk', 'qqpk', 'Other', 'qqpk'),
  ('Welocalize', 'welocalize', 'Other', 'welocalize'),
  ('Weex', 'weex', 'Other', 'weex'),
  ('Pixels', 'pixels', 'Other', 'pixels'),
  ('Inshallah', 'inshallah', 'Other', 'inshallah'),
  ('Toutiao', 'toutiao', 'Other', 'toutiao'),
  ('Alfursan', 'alfursan', 'Other', 'alfursan'),
  ('Verifykit', 'verifykit', 'Other', 'verifykit'),
  ('Wingmoney', 'wingmoney', 'Other', 'wingmoney'),
  ('Freecharge', 'freecharge', 'Other', 'freecharge'),
  ('Haraj', 'haraj', 'Other', 'haraj'),
  ('Citaprevia', 'citaprevia', 'Other', 'citaprevia'),
  ('Rummygold', 'rummygold', 'Other', 'rummygold'),
  ('Iyc', 'iyc', 'Other', 'iyc'),
  ('Fruitz', 'fruitz', 'Other', 'fruitz'),
  ('Gmx', 'gmx', 'Other', 'gmx'),
  ('Lalamove', 'lalamove', 'Other', 'lalamove'),
  ('Pinduoduo', 'pinduoduo', 'Other', 'pinduoduo'),
  ('Nextdoor', 'nextdoor', 'Other', 'nextdoor'),
  ('Weverse', 'weverse', 'Other', 'weverse'),
  ('Astropay', 'astropay', 'Other', 'astropay'),
  ('Escapefromtarkov', 'escapefromtarkov', 'Other', 'escapefromtarkov'),
  ('Hornet', 'hornet', 'Other', 'hornet'),
  ('Appen', 'appen', 'Other', 'appen'),
  ('Wepoker', 'wepoker', 'Other', 'wepoker'),
  ('Catawiki', 'catawiki', 'Other', 'catawiki'),
  ('Shopback', 'shopback', 'Other', 'shopback'),
  ('Keeta', 'keeta', 'Other', 'keeta'),
  ('Fans', 'fans', 'Other', 'fans'),
  ('Shabik', 'shabik', 'Other', 'shabik'),
  ('Handyticket', 'handyticket', 'Other', 'handyticket'),
  ('Abvbg', 'abvbg', 'Other', 'abvbg'),
  ('Unni', 'unni', 'Other', 'unni'),
  ('Dilmil', 'dilmil', 'Other', 'dilmil'),
  ('Vedantu', 'vedantu', 'Other', 'vedantu'),
  ('Dingtalk', 'dingtalk', 'Other', 'dingtalk'),
  ('Coffeemeetsbagel', 'coffeemeetsbagel', 'Other', 'coffeemeetsbagel'),
  ('3Fun', '3fun', 'Other', '3fun'),
  ('Codeium', 'codeium', 'Other', 'codeium'),
  ('Mosgram', 'mosgram', 'Other', 'mosgram'),
  ('Ankama', 'ankama', 'Other', 'ankama'),
  ('Hapi', 'hapi', 'Other', 'hapi'),
  ('Relicdao', 'relicdao', 'Other', 'relicdao'),
  ('Hacoo', 'hacoo', 'Other', 'hacoo'),
  ('Voovmeeting', 'voovmeeting', 'Other', 'voovmeeting'),
  ('Betinin', 'betinin', 'Other', 'betinin'),
  ('Icard', 'icard', 'Other', 'icard'),
  ('Wallapop', 'wallapop', 'Other', 'wallapop'),
  ('Finya', 'finya', 'Other', 'finya'),
  ('Cryptocom', 'cryptocom', 'Other', 'cryptocom'),
  ('Chargepoint', 'chargepoint', 'Other', 'chargepoint'),
  ('Lovoo', 'lovoo', 'Other', 'lovoo'),
  ('Marktplaats', 'marktplaats', 'Other', 'marktplaats'),
  ('Worldremit', 'worldremit', 'Other', 'worldremit'),
  ('Lidl', 'lidl', 'Other', 'lidl'),
  ('Webde', 'webde', 'Other', 'webde'),
  ('Tier', 'tier', 'Other', 'tier'),
  ('Muzz', 'muzz', 'Other', 'muzz'),
  ('Luup', 'luup', 'Other', 'luup'),
  ('Voggt', 'voggt', 'Other', 'voggt'),
  ('Seznam', 'seznam', 'Other', 'seznam'),
  ('Attapoll', 'attapoll', 'Other', 'attapoll'),
  ('Cryptonow', 'cryptonow', 'Other', 'cryptonow'),
  ('Erome', 'erome', 'Other', 'erome'),
  ('Serpapi', 'serpapi', 'Other', 'serpapi'),
  ('Sisal', 'sisal', 'Other', 'sisal'),
  ('Baihe', 'baihe', 'Other', 'baihe'),
  ('Blibli', 'blibli', 'Other', 'blibli'),
  ('Weareher', 'weareher', 'Other', 'weareher'),
  ('Riotgames', 'riotgames', 'Other', 'riotgames'),
  ('Hungrypanda', 'hungrypanda', 'Other', 'hungrypanda'),
  ('Perplexity', 'perplexity', 'Other', 'perplexity'),
  ('Nvidia', 'nvidia', 'Other', 'nvidia'),
  ('Yophone', 'yophone', 'Other', 'yophone'),
  ('Nielsen', 'nielsen', 'Other', 'nielsen'),
  ('Bananatok', 'bananatok', 'Other', 'bananatok'),
  ('Seated', 'seated', 'Other', 'seated'),
  ('Hellotalk', 'hellotalk', 'Other', 'hellotalk'),
  ('Courtyard', 'courtyard', 'Other', 'courtyard'),
  ('Arlens', 'arlens', 'Other', 'arlens'),
  ('Barq', 'barq', 'Other', 'barq'),
  ('Kktix', 'kktix', 'Other', 'kktix'),
  ('Salams', 'salams', 'Other', 'salams'),
  ('Xhsapp', 'xhsapp', 'Other', 'xhsapp'),
  ('Azar', 'azar', 'Other', 'azar'),
  ('Alchemy', 'alchemy', 'Other', 'alchemy'),
  ('Bcgame', 'bcgame', 'Other', 'bcgame'),
  ('Web3auth', 'web3auth', 'Other', 'web3auth'),
  ('Splitdrop', 'splitdrop', 'Other', 'splitdrop'),
  ('Immutableplay', 'immutableplay', 'Other', 'immutableplay'),
  ('Caliverse', 'caliverse', 'Other', 'caliverse'),
  ('Coze', 'coze', 'Other', 'coze'),
  ('Chagee', 'chagee', 'Other', 'chagee'),
  ('Huionepay', 'huionepay', 'Other', 'huionepay'),
  ('Gaode', 'gaode', 'Other', 'gaode'),
  ('Xmcom', 'xmcom', 'Other', 'xmcom'),
  ('Bykea', 'bykea', 'Other', 'bykea'),
  ('Taptapsend', 'taptapsend', 'Other', 'taptapsend'),
  ('Ploom', 'ploom', 'Other', 'ploom'),
  ('Tatneft', 'tatneft', 'Other', 'tatneft'),
  ('Walmart', 'walmart', 'Other', 'walmart'),
  ('Oldubil', 'oldubil', 'Other', 'oldubil'),
  ('Willhaben', 'willhaben', 'Other', 'willhaben'),
  ('Biedronka', 'biedronka', 'Other', 'biedronka'),
  ('Rappi', 'rappi', 'Other', 'rappi'),
  ('Depop', 'depop', 'Other', 'depop'),
  ('Guicheweb', 'guicheweb', 'Other', 'guicheweb'),
  ('Feels', 'feels', 'Other', 'feels'),
  ('Smitten', 'smitten', 'Other', 'smitten'),
  ('Boyaa', 'boyaa', 'Other', 'boyaa'),
  ('Soulapp', 'soulapp', 'Other', 'soulapp'),
  ('Lime', 'lime', 'Other', 'lime'),
  ('Spotify', 'spotify', 'Other', 'spotify'),
  ('Bearwww', 'bearwww', 'Other', 'bearwww'),
  ('Valora', 'valora', 'Other', 'valora'),
  ('Vestiairecollective', 'vestiairecollective', 'Other', 'vestiairecollective'),
  ('Ashleymadison', 'ashleymadison', 'Other', 'ashleymadison'),
  ('Muzmu', 'muzmu', 'Other', 'muzmu'),
  ('Band', 'band', 'Other', 'band'),
  ('Meituan', 'meituan', 'Other', 'meituan'),
  ('Fastmail', 'fastmail', 'Other', 'fastmail'),
  ('Csair', 'csair', 'Other', 'csair'),
  ('Atlasearth', 'atlasearth', 'Other', 'atlasearth'),
  ('Moveit', 'moveit', 'Other', 'moveit'),
  ('Ximalaya', 'ximalaya', 'Other', 'ximalaya'),
  ('Ourbit', 'ourbit', 'Other', 'ourbit'),
  ('Heybox', 'heybox', 'Other', 'heybox'),
  ('Eleme', 'eleme', 'Other', 'eleme'),
  ('Duolingo', 'duolingo', 'Other', 'duolingo'),
  ('Soarfun', 'soarfun', 'Other', 'soarfun'),
  ('Toobit', 'toobit', 'Other', 'toobit'),
  ('Superlogin', 'superlogin', 'Other', 'superlogin'),
  ('Doubao', 'doubao', 'Other', 'doubao'),
  ('League', 'league', 'Other', 'league'),
  ('Xunyou', 'xunyou', 'Other', 'xunyou'),
  ('Omi', 'omi', 'Other', 'omi'),
  ('Galaxyticketing', 'galaxyticketing', 'Other', 'galaxyticketing'),
  ('Activision', 'activision', 'Other', 'activision'),
  ('Watermelonvideo', 'watermelonvideo', 'Other', 'watermelonvideo'),
  ('Hudapp', 'hudapp', 'Other', 'hudapp'),
  ('Uu163', 'uu163', 'Other', 'uu163'),
  ('Sonyliv', 'sonyliv', 'Other', 'sonyliv'),
  ('Soulchill', 'soulchill', 'Other', 'soulchill'),
  ('Radiate', 'radiate', 'Other', 'radiate'),
  ('Getresponse', 'getresponse', 'Other', 'getresponse'),
  ('Playuzu', 'playuzu', 'Other', 'playuzu'),
  ('Capitaloneshopping', 'capitaloneshopping', 'Other', 'capitaloneshopping'),
  ('Dewupoizon', 'dewupoizon', 'Other', 'dewupoizon'),
  ('Vantage', 'vantage', 'Other', 'vantage'),
  ('Nimo', 'nimo', 'Other', 'nimo'),
  ('Airindia', 'airindia', 'Other', 'airindia'),
  ('Hoyoverse', 'hoyoverse', 'Other', 'hoyoverse'),
  ('Prodege', 'prodege', 'Other', 'prodege'),
  ('Upward', 'upward', 'Other', 'upward'),
  ('Pluxee', 'pluxee', 'Other', 'pluxee'),
  ('Papaen', 'papaen', 'Other', 'papaen'),
  ('Gfkcom', 'gfkcom', 'Other', 'gfkcom'),
  ('Chispadatinglatinos', 'chispadatinglatinos', 'Other', 'chispadatinglatinos'),
  ('Memelut', 'memelut', 'Other', 'memelut'),
  ('Freecoin', 'freecoin', 'Other', 'freecoin'),
  ('Meeff', 'meeff', 'Other', 'meeff'),
  ('Yuewen', 'yuewen', 'Other', 'yuewen'),
  ('Eventbrite', 'eventbrite', 'Other', 'eventbrite'),
  ('Seloger', 'seloger', 'Other', 'seloger'),
  ('Winee3', 'winee3', 'Other', 'winee3'),
  ('3D66', '3d66', 'Other', '3d66'),
  ('Minima', 'minima', 'Other', 'minima'),
  ('Qianwen', 'qianwen', 'Other', 'qianwen'),
  ('Magnolia', 'magnolia', 'Other', 'magnolia'),
  ('Biggg', 'biggg', 'Other', 'biggg'),
  ('Boletomovil', 'boletomovil', 'Other', 'boletomovil'),
  ('Hongguoduanju', 'hongguoduanju', 'Other', 'hongguoduanju'),
  ('Hotel101', 'hotel101', 'Other', 'hotel101'),
  ('Mail2world', 'mail2world', 'Other', 'mail2world'),
  ('Sapo', 'sapo', 'Other', 'sapo'),
  ('Jspp', 'jspp', 'Other', 'jspp'),
  ('Discoverhongkong', 'discoverhongkong', 'Other', 'discoverhongkong'),
  ('Icrypex', 'icrypex', 'Other', 'icrypex'),
  ('Egopensooq', 'egopensooq', 'Other', 'egopensooq'),
  ('Towns', 'towns', 'Other', 'towns'),
  ('Waug', 'waug', 'Other', 'waug'),
  ('Ari10', 'ari10', 'Other', 'ari10'),
  ('Hfmarkets', 'hfmarkets', 'Other', 'hfmarkets'),
  ('Poke', 'poke', 'Other', 'poke'),
  ('Immoscout24', 'immoscout24', 'Other', 'immoscout24'),
  ('Citygo', 'citygo', 'Other', 'citygo'),
  ('Cmtcuzdan', 'cmtcuzdan', 'Other', 'cmtcuzdan'),
  ('Paycell', 'paycell', 'Other', 'paycell')
on conflict (fivesim_product_code) do nothing;
